name: Check PR Status on Open and Synchronize

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-pr-status:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Related PRs from PR Body
        id: extract_related_prs
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          echo "Extracting related PR URLs from the '## Dependencies Pull Requests' section in the PR body..."

          # Extract the section "## Dependencies Pull Requests" and the table within it
          SECTION=$(echo "$PR_BODY" | awk '/## Dependencies Pull Requests/,/^## /')
          if [ -z "$SECTION" ]; then
            echo "No '## Dependencies Pull Requests' section found. Marking all as merged."
            exit 0
          fi

          # Extract related PR URLs from the table rows in the extracted section
          RELATED_PRS=$(echo "$SECTION" | grep -Eo '\| [^|]+ \| \[PR #[0-9]+\]\(https://github.com/[^/]+/[^/]+/pull/[0-9]+\)' | grep -Eo 'https://github.com/[^/]+/[^/]+/pull/[0-9]+' | tr '\n' ' ')

          if [ -z "$RELATED_PRS" ]; then
            echo "No related PRs found in the '## Dependencies Pull Requests' section. Marking all as merged."
            exit 0
          fi

          echo "Related PRs found: $RELATED_PRS"
          echo "related_prs=$RELATED_PRS" >> $GITHUB_OUTPUT

      - name: Check Status of Each Related PR
        if: success()
        run: |
          ALL_MERGED=true
          echo "Checking the status of each related PR..."

          for PR_URL in ${{ steps.extract_related_prs.outputs.related_prs }}; do
            PR_NUMBER=$(basename "$PR_URL")
            REPO_FULL_NAME=$(echo "$PR_URL" | sed 's|https://github.com/||' | sed 's|/pull/.*||')

            # Fetch the PR status using GitHub API
            PR_STATUS=$(curl -H "Authorization: Bearer ${{ secrets.USER_ACTION_TOKEN }}" \
              "https://api.github.com/repos/$REPO_FULL_NAME/pulls/$PR_NUMBER" | jq -r '.merged')

            if [ "$PR_STATUS" != "true" ]; then
              ALL_MERGED=false
              echo "Related PR #$PR_NUMBER in repository $REPO_FULL_NAME is NOT merged."
            else
              echo "Related PR #$PR_NUMBER in repository $REPO_FULL_NAME is merged."
            fi
          done

          # If all related PRs are merged, set success; otherwise, exit with failure
          if [ "$ALL_MERGED" == "true" ]; then
            echo "All related PRs are merged."
            exit 0
          else
            echo "Not all related PRs are merged. Exiting."
            exit 1
          fi
