name: Dispatch Triggered Open PRs Check

on:
  repository_dispatch:
    types: [dispatch-triggered-open-prs-check]
  workflow_dispatch:  # Allows manual triggers if needed

jobs:
  dispatch-triggered-open-prs-check:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch All Open PRs
        id: fetch_prs
        run: |
          echo "Fetching all open PRs in the repository..."
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.USER_ACTION_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open")

          # Extract PR numbers, bodies, branches, and SHAs from the response
          prs=$(echo "$response" | jq -r '.[] | {number: .number, body: .body, branch: .head.ref, sha: .head.sha} | @base64')

          if [ -z "$prs" ]; then
            echo "No open pull requests found."
            exit 0
          fi

          # Iterate over each PR and check status
          for pr in $prs; do
            pr_json=$(echo "$pr" | base64 --decode)
            pr_number=$(echo "$pr_json" | jq -r '.number')
            pr_body=$(echo "$pr_json" | jq -r '.body')
            pr_branch=$(echo "$pr_json" | jq -r '.branch')
            pr_sha=$(echo "$pr_json" | jq -r '.sha')

            echo "Processing PR #$pr_number on branch $pr_branch"

            # Check related PRs status inline for each PR
            echo "Checking related PRs for PR #$pr_number"
            workflow_runs=$(curl -s -H "Authorization: Bearer ${{ secrets.USER_ACTION_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=pull_request&branch=$pr_branch" | jq '.workflow_runs')

            # Find the latest run specific to this PR
            latest_run_id=$(echo "$workflow_runs" | jq -r "[.[] | select(.pull_requests[].number == $pr_number)][0].id")

            if [ -n "$latest_run_id" ] && [ "$latest_run_id" != "null" ]; then
              echo "Re-running workflow for PR #$pr_number with run ID $latest_run_id"
              curl -X POST \
                -H "Authorization: Bearer ${{ secrets.USER_ACTION_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$latest_run_id/rerun"
            else
              echo "No recent workflow run found for PR #$pr_number"
            fi
          done
