name: Trigger Repository Dispatch on Libraries that uses this Library

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch event
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "check-related-prs", "client_payload": { "repository": "${{ github.repository }}", "pull_request": "${{ github.event.pull_request.number }}", "action": "${{ github.event.action }}", "state": "${{ github.event.pull_request.state }}" }}' \
          https://api.github.com/repos/Playrom/MyLibrary/dispatches

          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type": "check-related-prs", "client_payload": { "repository": "${{ github.repository }}", "pull_request": "${{ github.event.pull_request.number }}", "action": "${{ github.event.action }}", "state": "${{ github.event.pull_request.state }}" }}' \
          https://api.github.com/repos/Playrom/App/dispatches
